# NAME: Dawei Huang and Nathan Smith 
# EMAIL: daweihuang@ucla.edu and nathan.smith@ucla.edu
# ID: 304792166 and 704787554


default: build

build:
	gcc -g -Wall -Wextra -o lab3a lab3a.c

clean:
	rm -f lab3a lab3a-704787554.tar.gz

dist:
	tar -zcvf lab3a-704787554.tar.gz Makefile README lab3a.c
